<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>pathofsight</AssemblyName>
    <Version>0.1.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.IO" />
    <InternalsVisibleTo Include="pathofsight.Tests" />
    <ProjectReference Include="../../vendor/POE2Radar.Core/POE2Radar.Core.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <EmbeddedResource Include="dashboard.html" />
    <EmbeddedResource Include="Art/eye.txt" />
  </ItemGroup>
</Project>

